### ISSUE TITLE
Improve online docs

### ISSUE THREAD

**Issue by kevin-bates** [SparkTC/enterprise_gateway#155]
We need to make another pass to our online docs.  Here are some areas that need attention...

[Enterprise Installation](http://9.30.252.137/dist/docs/getting-started.html#enterprise-installation) - need to remove references to down-load server, among other things.
[Use Cases](http://9.30.252.137/dist/docs/uses.html) - need more examples!
[Feature](http://9.30.252.137/dist/docs/features.html) - can use more detail.
[Troubleshooting](http://9.30.252.137/dist/docs/troubleshooting.html) - should add some entries relative to yarn and distributed troubleshooting
[Integration Testing](http://9.30.252.137/dist/docs/devinstall.html#integration-testing) - this reads more like a blog.  We should either include our integration tests in the repo and then update to reference those files or turn this into a blog for the upcoming website - but add more concrete information.

**Comment by lresende** [comment]
Overall review and updates have been done, documentation is now live at readthedocs website:
http://jupyter-enterprise-gateway.readthedocs.io/en/latest/
